### PR TITLE
fix some errors in the Kubernetes Quickstart

### PR DESCRIPTION
**Pull request by bixu**

### CODE REVIEW

**Review by puckpuck — APPROVED** [review]

**Comment by puckpuck** [comment]
lgtm

**Comment by eanakashima** [comment]
Thanks, @bixu ! 👋  😄

**Comment by bixu** [comment]
I wore my granola (Patagonia) vest while committing that patch. Seemed only natural :)

**Comment by eanakashima** [comment]
Excellent choice :)

**Pull request merged**
