### PR TITLE
add metrics collection support

### PR DESCRIPTION
**Pull request by puckpuck**
PR to add functionality we have for metrics collection

To recap the functionality is largely lifted from the [kubeletstats](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/receiver/kubeletstatsreceiver) receiver as part of the OpenTelemetry Collector. Parts were changed to simplify the internal data structures. Pod labels are automatically added to pods/containers/volumes, and status for pod/container is also added. All metrics for a given resource will be emitted as a single event into Honeycomb

Enabling it is done via a new `metrics` configuration object.

```yaml
metrics:
  enabled: true
  interval: 10s
  dataset: kubernetes-metrics
  clusterName: k8s-cluster
  endpoint: k8s-node-name:10250
  omitLabels:
    - "controller-revision-hash"
  metricGroups:
    - node
    - pod
    - container
    - volume
  additionalFields:
    global_field: "my-value"
```

For the above configuration, only the `enabled: true` property is required.  The `endpoint` configuration property may be removed since the agent already requires a `NODE_NAME` environment variable.  By default collection will be for the `node` and `pod` metric groups.

### CODE REVIEW

**Comment by puckpuck** [comment]
Test cases all set, and code is ready and stable.  Ready to get this reviewed.

**Comment by irvingpop** [comment]
hey @puckpuck @lizthegrey @paulosman 
Is there any reason _not_ to approve and merge this PR now?

**Comment by paulosman** [comment]
> hey @puckpuck @lizthegrey @paulosman
> Is there any reason _not_ to approve and merge this PR now?

Just bandwidth - will need someone to give it a whirl. Will ask around for people willing to give it a look.

**Comment by puckpuck** [comment]
We do have multiple prospects/customers running this today.

**Comment by irvingpop** [comment]
Some testing notes & feedback.   Tried this today on an EKS 1.18 cluster, using [the quickstart.yaml from the PR](https://raw.githubusercontent.com/honeycombio/honeycomb-kubernetes-agent/puckpuck.metrics-support/examples/quickstart.yaml)

* had to change the image tag to `honeycombio/honeycomb-kubernetes-agent:2.1.0-beta4` - since `2.1.0` doesn't exist yet
* I did encounter some RBAC permissions errors, the scope needs to be expanded for honeycomb-serviceaccount:

```
time="2020-11-12T00:46:02Z" level=error msg="Could not retrieve stats" error="kubelet request GET https://ip-192-168-81-33.us-east-2.compute.internal:10250/stats/summary failed - \"403 Forbidden\", response: \"Forbidden (user=system:serviceaccount:kube-system:honeycomb-serviceaccount, verb=get, resource=nodes, subresource=stats)\""
time="2020-11-12T00:46:12Z" level=error msg="Could not retrieve metadata" error="kubelet request GET https://ip-192-168-81-33.us-east-2.compute.internal:10250/pods failed - \"403 Forbidden\", response: \"Forbidden (user=system:serviceaccount:kube-system:honeycomb-serviceaccount, verb=get, resource=nodes, subresource=proxy)\""
```

* I adjusted like so:
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: honeycomb-serviceaccount
  namespace: kube-system
rules:
  - apiGroups:
    - "*"
    resources:
    - pods
    - nodes/stats
    - nodes/proxy
    verbs:
    - list
    - watch
    - get
```


and then, tada! 

image

**Review by paulosman — APPROVED** [review]
🎉

**Pull request merged**
